ALTER TABLE SalesHistory
ADD LocationNotes VARCHAR(100) NULL
GO
UPDATE SalesHistory SET LocationNotes = CAST(NEWID() AS VARCHAR(100)) + CAST(NEWID() AS VARCHAR(100))
GO
ALTER TABLE SalesHistory
ALTER COLUMN LocationNotes VARCHAR(100) NOT NULL
GO
ALTER INDEX ALL ON SalesHistory REBUILD
GO
